- name: Stop Firewall Service
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "7"

- name: Stop Firewall Service
  service:
    name: iptables
    state: stopped
    enabled: no
  when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "6"

- name: Stop Firewall Service
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "7"


