- name: Install Default packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ packages }}"
  when: ansible_facts['distribution'] == "CentOS"

- name: Install Default Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ packages }}"
  when: ansible_facts['distribution'] == "Ubuntu"
