---
# tasks file for baselineconf
- name: Install Basic Packages
  include_tasks: install_packages.yaml

- name: Configuring security context 
  include_tasks: configure_selinux.yaml

- name: Stop firewall service
  include_tasks: configure_firewall.yaml

- name: Update Hostname 
  include_tasks: update_hostname.yaml

- name: Optimize configuration
  include_tasks: optimize_ssh.yaml

