- name: Remove old Hosts file entry if exists
  lineinfile:
    path: /tmp/hosts
    backup: yes
    regexp: "{{ hostname }}"
    state: absent
  when: hostname  != 'localhost'
- name: Add hosts file entry
  lineinfile:
    path: /tmp/hosts
    line: '{{ ansible_default_ipv4.address }} {{ hostname }}'
  when: hostname != 'localhost'


